import React from 'react'
import './NotFound.css'
import { Link } from 'react-router-dom'

const NotFound = () => {
    return (
      <div className=''>
        <div>
          <title>Rick and Morty | Page Not Found</title>
          <meta name="description" content="Generated by create next app" />
        </div>
        <div className=''>
          <h1>Oops!</h1>
          <p>We can't seem to find the page you are looking for.</p>
          <Link to="/">
            <button>Go Back Home</button>
          </Link>
        </div>
        <img src='https://img.freepik.com/free-vector/oops-404-error-with-broken-robot-concept-illustration_114360-5529.jpg?w=2000' alt="errorlogo" />
      </div>
    )
  }
  
  export default NotFound